# Generated by Django 5.2.6 on 2025-09-08 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProcessingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('region', models.CharField(default='IL', help_text='Country code for phone number parsing', max_length=5)),
                ('sample_fps', models.IntegerField(default=4, help_text='Frames per second to analyze')),
                ('min_confidence', models.IntegerField(default=55, help_text='Minimum OCR confidence (0-100)')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e164_number', models.CharField(help_text='Phone number in E164 format', max_length=20)),
                ('national_number', models.CharField(help_text='Phone number in national format', max_length=30)),
                ('first_seen_seconds', models.FloatField(help_text='Time in video when first seen')),
                ('frame_count', models.IntegerField(help_text='Number of frames where this number appeared')),
                ('raw_text_examples', models.TextField(help_text='Examples of raw text where number was found')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='api.videoprocessingtask')),
            ],
            options={
                'ordering': ['first_seen_seconds', 'e164_number'],
                'unique_together': {('task', 'e164_number')},
            },
        ),
    ]
