# Generated by Django 5.2.6 on 2025-09-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprocessingtask',
            name='current_frame',
            field=models.IntegerField(default=0, help_text='Current frame being processed'),
        ),
        migrations.AddField(
            model_name='videoprocessingtask',
            name='current_message',
            field=models.TextField(blank=True, help_text='Current processing message'),
        ),
        migrations.AddField(
            model_name='videoprocessingtask',
            name='progress',
            field=models.IntegerField(default=0, help_text='Processing progress percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='videoprocessingtask',
            name='total_frames',
            field=models.IntegerField(default=0, help_text='Total frames to process'),
        ),
    ]
